version: '2'
services:
  wscef:
    build: .
    devices:
      - /dev/snd:/dev/snd
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/home/ff/.Xauthority
      - HOST_HOSTNAME=${HOSTNAME}
    cpuset: '0'
    mem_limit: 512M
    volumes:
      - /dev/shm:/dev/shm:Z
      - /tmp/.X11-unix:/tmp/.X11-unix:Z
      - ${XAUTHORITY}:/tmp/.docker.xauth:ro,Z
